apiVersion: v1
kind: Service
metadata: 
  name: mysql-svc
  namespace: test-ns
spec:
  clusterIP: None 
  selector:
    app: mysqldb
  ports:
  - port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: mysqldb-statefulset
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mysqldb
  serviceName: mysql-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        volumeMounts: 
        - name: mysqlvol
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
  volumeClaimTemplates:
  - metadata:
      name: mysqlvol
    spec: 
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
